from typing import Protocol


class ActiveScanner(Protocol):
    @property
    def configured(self) -> bool: ...

    async def check_availability(self) -> bool: ...

    async def start_authorized_scan(self, target: str) -> str: ...

    async def poll_scan_progress(self, scan_id: str) -> int: ...

    async def retrieve_alerts(self, target: str) -> list[dict]: ...
