from typing import Protocol

from app.models import ActiveScanJob, ActiveScanRequest, Finding, ScannerCapability


class ActiveScanner(Protocol):
    def validate_configuration(self) -> ScannerCapability: ...

    async def start_scan(self, request: ActiveScanRequest) -> ActiveScanJob: ...

    async def get_status(self, job_id: str) -> ActiveScanJob: ...

    async def get_findings(self, job_id: str) -> list[Finding]: ...

    async def cancel_scan(self, job_id: str) -> ActiveScanJob: ...
